<?php
$person2['name'] = "Nnenna";
$person2['nationality'] = "Nigeria";
$person2['height'] = "tall";
$person2['complexion'] = "dark";
$person3['name'] = "Nancy";
$person3['nationality'] = "Nigeria";
$person3['height'] = "tall";
$person3['complexion'] = "fair";
$person4['name'] = "Uju";
$person4['nationality'] = "Ghana";
$person4['height'] = "short";
$person4['complexion'] = "dark";
$person5['name'] = "Jude";
$person5['nationality'] = "USA";
$person5['height'] = "tall";
$person5['complexion'] = "dark";
$person6['name'] = "Ada";
$person6['nationality'] = "Spain";
$person6['height'] = "tall";
$person6['complexion'] = "fair";
$person7['name'] = "Seun";
$person7['nationality'] = "Qatar";
$person7['height'] = "tall";
$person7['complexion'] = "Dark";
$person8['name'] = "Bruce";
$person8['nationality'] = "Sweden";
$person8['height'] = "tall";
$person8['complexion'] = "fair";
$person9['name'] = "Yul";
$person9['nationality'] = "Niger";
$person9['height'] = "short";
$person9['complexion'] = "fair";
$person10['name'] = "Ade";
$person10['nationality'] = "Uk";
$person10['height'] = "short";
$person10['complexion'] = "fair";
echo "I am $person2[name], $person2[height]and $person2[complexion] living in $person2[nationality]";
'\n';
echo "I am $person3[name], $person3[height] and $person3[complexion] living in $person3[nationality]";
echo "I am $person4[name], $person4[height] and $person4[complexion] living in $person4[nationality]";
echo "I am $person5[name], $person5[height] and $person5[complexion] living in $person5[nationality]";
echo "I am $person6[name], $person6[height] and $person6[complexion] living in $person6[nationality]";
echo "I am $person7[name], $person7[height] and $person7[complexion] living in $person7[nationality]";
echo "I am $person8[name], $person8[height] and $person8[complexion] living in $person8[nationality]";
echo "I am $person9[name], $person9[height] and $person9[complexion] living in $person9[nationality]";
echo "I am $person10[name], $person10[height] and $person10[complexion] living in person10[nationality]";
?>
